version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      composer:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      npm:
        patterns:
          - "*"
